### PR TITLE
Fixed payment errors handling

### PR DESCRIPTION
**Pull request by GregOriol**
Currently, when an error occurs during a payment, the error data is not saved and the payment is in the UNKNOWN state.

An error can be triggered with one of the Stripe error test cards.

The reason for this issue is that Stripe's PaymentIntent.create call throws a PaymentCard exception (which is a StripeException), and therefore is not processed with the metadata retrieval and the state check/set and instead gets thrown all the way up as an exception.

Obviously a payment should not be in the UNKNOWN state, and having this causes many issues (no retries, no explicit error message, ...).

I'm trying here a fix by retrieving the PaymentIntent and passing it into the process that should have been triggered. I haven't found a cleaner way than using the charge_id from the CardException, retrieving the charge then using it's paymentintent_id to get it. If anyone has a better idea?

### CODE REVIEW

**Comment by pierre** [comment]
Thanks!

> Obviously a payment should not be in the UNKNOWN state, and having this causes many issues (no retries, no explicit error message, ...).

👍 

> I'm trying here a fix by retrieving the PaymentIntent and passing it into the process that should have been triggered. I haven't found a cleaner way than using the charge_id from the CardException, retrieving the charge then using it's paymentintent_id to get it. If anyone has a better idea?

An alternative would be to have a new `addResponse` DAO API, which doesn't rely on passing a `PaymentIntent` parameter (which is just used to store the metadata). That being said, [CardException](https://github.com/stripe/stripe-java/blob/master/src/main/java/com/stripe/exception/CardException.java) doesn't have much metadata, so we might be better off pulling the full object again.

Would you be able to add a test for this? Something similar to https://github.com/killbill/killbill-stripe-plugin/blob/074a829dbf0819a498d4bd9d588056345e766734/src/test/java/org/killbill/billing/plugin/stripe/TestStripePaymentPluginApi.java#L314 maybe?

**Comment by GregOriol** [comment]
The "problem" with using the CardException's data is that... it lacks data! It's so limited. The actual response from the API seems to include the details of the PaymentIntent but the exception doesn't seem to provide any way to get it...
And I think it's best to have the same data for this case as for other responses, with the same keys like last_charge, status, ... It will be easier to process.

For the test, I don't understand how to make one with a fail test card: can't find out how to set the card number here?!

**Comment by pierre** [comment]
> The "problem" with using the CardException's data is that... it lacks data! It's so limited. The actual response from the API seems to include the details of the PaymentIntent but the exception doesn't seem to provide any way to get it...

It could be a limitation of their client: have you reached out to Stripe developers?

> And I think it's best to have the same data for this case as for other responses, with the same keys like last_charge, status, ... It will be easier to process.

Agreed.

> For the test, I don't understand how to make one with a fail test card: can't find out how to set the card number here?!

We use a working payment method for tests: https://github.com/killbill/killbill-stripe-plugin/blob/074a829dbf0819a498d4bd9d588056345e766734/src/test/java/org/killbill/billing/plugin/stripe/TestStripePaymentPluginApi.java#L662

Stripe publishes the list of magic failing test cards here: https://stripe.com/docs/testing#cards-responses

**Comment by pierre** [comment]
> That might be due to a version of java? (1.8 here)
> [...]
> Then, previously I was building with the command `mvn clean package -Dmaven.test.skip=true` and had to replace it with `mvn -DskipTests=true clean package` for the branch `dependencies-updates` otherwise there were some strange errors (checks failing?).

That's odd (x2). Which version of Maven?

> Finally the problem with the merge is that `import com.stripe.model.Charge;` was in the file before, but doesn't seem to be there anymore, but this has changed in the branch I guess, as it was there before independently of this PR. I'm rebasing the PR on the branch and readding the line to fix it!

All good, thanks! This is now on the `dependencies-updates` branch and will be in 7.1.0.

**Pull request merged**
