### PR TITLE
Extend create Stripe customer on any PaymentMethod

### PR DESCRIPTION
**Pull request by Jimmy-Newtron**
I have tested on my stripe account and there is no failing test

I have a doubt on the meaning of the **setDefault** parameter when adding the payment method

### CODE REVIEW

**Review by pierre — APPROVED** [review]
> I have a doubt on the meaning of the setDefault parameter when adding the payment method

`setDefault` is supposed to map the default payment method on the Kill Bill account to the default payment method on the payment gateway account, if the concept exists in the gateway.

Looking at https://stripe.com/docs/api/customers/create, it seems that this is done automatically for us when creating the customer?
image

**Comment by Jimmy-Newtron** [comment]
> Looking at https://stripe.com/docs/api/customers/create, it seems that this is done automatically for us when creating the customer?

Yes it is the case for Sources and Tokens, but not for the PaymentMethods that requires an additional parameter.
image

I have added the parameter by default in any case without any check, but maybe I am wrong

Have a look at https://github.com/killbill/killbill-stripe-plugin/pull/91/files#diff-82106774487ff108cdbcfd3289ed38fc9eb69c6e41390c3fc44308484107c429R308

```
"invoice_settings", ImmutableMap.of("default_payment_method", paymentMethodIdInStripe));
```

**Comment by Jimmy-Newtron** [comment]
> * I suspect, due to the name of the parameter, this only applies to Stripe billing, which would be odd to use in conjunction with Kill Bill

If the parameter is not set the new payment method is not stored as the default for the created customer

**Comment by Jimmy-Newtron** [comment]
image

Run the test with different **setDefault** values:

- false => there is a payment method
- true => there is a payment method **default**

image

vs

image

**Comment by Jimmy-Newtron** [comment]
Let me know when a new release will contain this code

Thanks in advance @pierre

**Comment by pierre** [comment]
Thanks for the detailed testing.

Tagging in @sbrossie who knows more about these Stripe APIs - to me, since Kill Bill always passes the right payment method to use in Stripe, this `default_payment_method` parameter should have no effect, but I might be missing something 🤔

**Comment by sbrossie** [comment]
> Thanks for the detailed testing.
> 
> Tagging in @sbrossie who knows more about these Stripe APIs - to me, since Kill Bill always passes the right payment method to use in Stripe, this `default_payment_method` parameter should have no effect, but I might be missing something 🤔

If we want to rely on the Stripe customer default payment method functionality, then I think setting the `invoice_settings.default_payment_methods` makes sense. If however, we are relying on Kill Bill's default payment method to correctly identify the (default) payment method of choice, then I am not sure this is necessary (and actually we could end up with 2 systems thinking they have different default payment methods).


@Jimmy-Newtron Could you explain why setting the default payment method in Stripe is relevant and how this is used?

**Comment by Jimmy-Newtron** [comment]
@sbrossie in fact I discovered that it is not relevant when you are relying on Kill Bill.

Anyway I find a little more consistent to have the same setup for the customer in Stripe and the Kill Bill account.

In fact there are no benefits neither disadvantages when we set the ```invoice_settings.default_payment_methods```, but it is my humble opinion.

**PS** there can be an hybrid use case in some enterprise where some application rely on Kill Bill  and other applications are directly connected to Stripe so keeping consistency makes sense to me

**Comment by sbrossie** [comment]
>  there can be an hybrid use case in some enterprise where some application rely on Kill Bill and other applications are directly connected to Stripe so keeping consistency makes sense to me

Yes.. Except there is no way to guarantee consistency, we end up with 2 systems owing the truth with regards to default PM, so I would vote not not set it at the Stripe level.

**Review by pierre — APPROVED** [review]
Thanks!

**Pull request merged**
